// Middle-Section > Dex-Choose-Section > Dex-Card
export const DexCardData = [
  {
    icon: "/images/transaction-icon.svg",
    heading: "Low Fees & Single Transaction",
    text: "Swappers benefit from our cross-chain liquidity to swap, bridge and receive gas fees in a single transaction and with low fees",
  },
  {
    icon: "/images/benefits-icon.svg",
    heading: "SPACE Holder Benefits",
    text: "SPACE holders enjoy the price appreciation of a deflationary asset while veSPACE holders receive a share of the fees generated by the protocol",
  },
  {
    icon: "/images/revenue-icon.svg",
    heading: "Earn 2x Revenue",
    text: "Liquidity providers benefit from dual revenue generation for twice the APY while single-staking assets",
  },
  {
    icon: "/images/suite-icon.svg",
    heading: "Decentralized Trading Suite",
    text: "Traders will, depending on their skills and time allocation, benefit from automated yield optimisation strategies or enjoy a decentralised platform to swap, short, long and leverage.",
  },
  {
    icon: "/images/strategies-icon.svg",
    heading: "Automated Farming Strategies",
    text: "Farmers and yield optimizers will enjoy automated strategies to increase rewards while keeping risk in check. Earning money has never been easier.",
  },
];
